# File to run MIPLIB Instances

###  Library loading

In [75]:
%load_ext autoreload
%autoreload

import numpy as np
import scipy as sp
import scipy.sparse

import scipy.sparse.linalg
import copy


from Cuts import *
from ReprVars import *
from CPLEXInterface import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Loading the MIPLIB file, converting to standard form and storing it in another file, and solving the std form

In [87]:
filename = 'n3-3'
prefix = './MIPLIB/'
postfix = '.mps'
C_org = cplex.Cplex()
C_org.read(prefix+filename+postfix)
C = Cplex2StdCplex(prefix+filename+postfix, MIP  = True, verbose = True)
cont_var = np.array([1 if i=='C' else 0 for i in C.variables.get_types()])
int_var = 1-cont_var
C.set_problem_type(C.problem_type.LP)
C.write(prefix+filename+'_std'+postfix)
# LPSolution = getfromCPLEX(C, verbose=1, ForceSolve=True, tableaux=False)
# print(LPSolution["Objective"])


Selected objective sense:  MINIMIZE
Selected objective  name:  R2426
Selected RHS        name:  B
Selected bound      name:  BOUND

Selected objective sense:  MINIMIZE
Selected objective  name:  R2426
Selected RHS        name:  B
Selected bound      name:  BOUND
Constraint matrices extracted. Eq:  2181  Ineq:  244  Nvar:  9028
Upper bound constraints added. Eq:  2181  Ineq:  610  Nvar:  9028
Lower bound constraints added. Eq:  2181  Ineq:  610  Nvar:  9028
Slacks added. Eq:  2181  Ineq:  610  Nvar:  9638


Default column names x1, x2 ... being created.
Default row    names c1, c2 ... being created.


In [90]:
C.solve()
C_org.set_problem_type(C.problem_type.LP)
C_org.solve()
# C_org.solution.status[C_org.solution.get_status()]
print(C.solution.get_objective_value(),C_org.solution.get_objective_value())

CPXPARAM_Read_DataCheck                          1
CPXPARAM_Read_APIEncoding                        "UTF-8"
CPXPARAM_MIP_Strategy_CallbackReducedLP          0
Parallel mode: deterministic, using up to 8 threads for concurrent optimization.
Tried aggregator 1 time.
LP Presolve eliminated 369 rows and 817 columns.
Aggregator did 213 substitutions.
Reduced LP has 2209 rows, 8608 columns, and 33694 nonzeros.
Presolve time = 0.03 sec. (5.27 ticks)
Initializing dual steep norms . . .

Iteration log . . .
Iteration:     1   Dual objective     =           245.000000
Iteration:    93   Dual objective     =          1495.000000
Iteration:   171   Dual objective     =          1495.000000
Perturbation started.
Iteration:   202   Dual objective     =          1495.000000
Iteration:   286   Dual objective     =          1605.000432
Iteration:   363   Dual objective     =          1955.000384
Iteration:   443   Dual objective     =          1955.000476
Iteration:   525   Dual objective     =        

In [91]:
print(C_org.variables.get_num(), C.variables.get_num())


9028 9638


In [54]:
# Get the set of basic variables from CPLEX
Basics = np.array(C.solution.basis.get_basis()[0])

# Total number of variables in the problem
nVar = np.size(Basics)

# # Indices corresponding to basic and non-basic variables
B_in = np.where(Basics)[0]
N_in = np.array(list(set(range(nVar))-set(B_in)))


# # The set of constraints in the problem
rows = C.linear_constraints.get_rows()

# # The RHS of the Ax = b constraints
b = C.linear_constraints.get_rhs()
print(len(b))
B_in.shape
print(C.solution.basis.get_basis())

2791
([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [62]:
C.solve()

CPXPARAM_Read_DataCheck                          1
CPXPARAM_Read_APIEncoding                        "UTF-8"
CPXPARAM_MIP_Strategy_CallbackReducedLP          0
Parallel mode: deterministic, using up to 8 threads for concurrent optimization.
Bound infeasibility column 'x9000'.
Presolve time = 0.02 sec. (1.18 ticks)


In [63]:
soln = np.array(C.solution.get_values())
temp = np.linalg.norm(np.array([0 if i == 'E' else 1 for i in C.linear_constraints.get_senses()]))
print("Num Var: ", C.variables.get_num(), 
      "\n Num Const: ", C.linear_constraints.get_num(), 
      "\n Incorrect senses?", temp,
     "\n RHS length:", len(C.linear_constraints.get_rhs()))

CPLEX Error  1217: No solution exists.


CplexSolverError: CPLEX Error  1217: No solution exists.

In [ ]:
t1 = LPSolution["Tableaux_NB"]
# print(t1.tocoo())
t2 = np.random.randint(0,2,(338,))==1
print(t1.tocsr()[t2,:].tocsc())


In [175]:
A = np.random.randint(0,10,(4,3))
A2 = A[np.array([0,1,1,0])==1,]
print(A,A2[:,0])

[[4 8 1]
 [2 7 6]
 [6 4 6]
 [4 7 4]] [2 6]


### Adding GMI cuts corresponding to all rows where it would be valid

In [17]:
(A_GMI, b_GMI) = GMI(
    LPSolution["Tableaux"][:, LPSolution["NonBasic"]], 
    LPSolution["Solution"], 
    int_var[LPSolution["Basic"]].astype(int), 
    cont_var[LPSolution["NonBasic"]].astype(int)
)

C_GMI = addCuts2Cplex(filename = prefix+filename+'_std'+postfix,
                     NB = LPSolution["NonBasic"],
                     A_cut = A_GMI,
                     b_cut = b_GMI)
GMIans = getfromCPLEX(C_GMI, tableaux = False, basic = False)
GMIans["Objective"]


Selected objective sense:  MINIMIZE
Selected objective  name:  obj
Selected RHS        name:  rhs


1.0

# Cuts based of Crosspolytopes

###  Generating row choice, mu choice and f choice for X and GX cuts

In [18]:
x_B = -LPSolution["Solution"][LPSolution["Basic"]]
nCuts = 5
nRows = 10
ans = Rows4Xcut(x_B, nRows, nCuts, int_var[LPSolution["Basic"]], 1)

### Generating X cuts


In [11]:
(A_X, b_X) = XLift(
    LPSolution["Tableaux_NB"].todense(), 
    LPSolution["Sol_Basic"],
    ans["RowMat"],
    ans["muMat"],
    cont_var[LPSolution["NonBasic"]].astype(int)
)

C:\Users\ssrir\Dropbox\code\ML4IP\Cuts.py:227: RuntimeWarning: divide by zero encountered in double_scalars
  a[i,0] = mu[i,0]/b[i,0]


KeyboardInterrupt: 

 ### Generating GX cuts

In [19]:
(A_GX, b_GX) = GXLift(
    LPSolution["Tableaux_NB"], 
    LPSolution["Sol_Basic"],
    ans["RowMat"],
    ans["muMat"],
    ans["fMat"],
    cont_var[LPSolution["NonBasic"]].astype(int),
    sparse = True,
    verbose = False
)
# print(A_GX, b_GX)
# print(LPSolution["Tableaux"][:, LPSolution["NonBasic"]])

cut 0generated
cut 1generated
cut 2generated
cut 3generated
cut 4generated


In [20]:
C_GX = addCuts2Cplex(filename = prefix+filename+'_std'+postfix,
                     NB = LPSolution["NonBasic"],
                     A_cut = A_GX,
                     b_cut = b_GX)
GMIans = getfromCPLEX(C_GX, tableaux = False, basic = False, TablNB = False)
print(GMIans["Objective"])
print(A_GX)


Selected objective sense:  MINIMIZE
Selected objective  name:  obj
Selected RHS        name:  rhs
1.3685531968097622
[[ 1.          1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          1.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.45716883  0.          0.          0.          0.43112886  0.          0.
   0.          0.          0.          0.          0.          0.45716883
   0.45716883  0.45716883  0.          0.43112886  0.43112886  0.43112886
   0.          0.          0.          0.          0.          0.          0.
   0.45716883  0.          0.          0.          0.43112886  0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.   

In [96]:
C_GX.solution.status[C_GX.solution.get_status()]

'optimal'

In [6]:
NBtable = LPSolution["Tableaux"][:, LPSolution["Basic"]]
NBtable = NBtable.tolist()
for i in NBtable:
    print(i)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [460]:
print(C.variables.get_num(), C.linear_constraints.get_num())

507 338


In [467]:
np.shape(LPSolution["Tableaux"][:, LPSolution["NonBasic"]])

(338, 169)

In [469]:
C.solve()
# LPSolution["Tableaux"][0, LPSolution["NonBasic"]]