In [37]:
%load_ext autoreload
%autoreload 2
from ReprVars import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [38]:
f = np.arange(5)
Aeq = np.random.randint(0,10,(3,5))
beq = np.array([5,5,3])
cont = np.array([0,0,0,0,1])

In [39]:
MIP1 = MIP(
    form = 1,
    data = {'f' : f, 'Aeq' : Aeq, 'beq' : beq, 'cont' : cont, 'A':np.array([[]]), 'b': np.array([[]]), 'lb':np.array([-np.inf]*5), 'ub':np.array([np.inf]*5)},
    filenames = False
)
MIP2 = MIP(
    form = 2,
    data = {'f' : f, 'Aeq' : Aeq, 'beq' : beq, 'cont' : cont, 'A':np.array([[]]), 'b': np.array([[]]), 'lb':np.array([-np.inf]*5), 'ub':np.array([np.inf]*5)},
    filenames = False
)

In [40]:
print(MIP1.size(), MIP2.size())

{'nInt': 4, 'nCons': 3, 'nVar': 5} {'nInt': 8.0, 'nCons': 3, 'nVar': 10}


In [42]:
print(MIP1.f, '\n', MIP1.Aeq, MIP1.beq)
print()
print(MIP2.f, '\n', MIP2.Aeq, MIP2.beq)

[0 1 2 3 4] 
 [[1 2 2 1 2]
 [3 0 9 1 2]
 [0 8 4 1 5]] [5 5 3]

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 0.]
 [-1.]
 [-2.]
 [-3.]
 [-4.]] 
 [[ 1.  2.  2.  1.  2. -1. -2. -2. -1. -2.]
 [ 3.  0.  9.  1.  2. -3.  0. -9. -1. -2.]
 [ 0.  8.  4.  1.  5.  0. -8. -4. -1. -5.]] [[ 5.]
 [ 5.]
 [ 3.]]
